Python_Black_Belt_01/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include("apps.log_reg.urls", namespace = "log_reg")),
    url(r'^wishlist/', include("apps.wish_list.urls", namespace = "wish_list")),
]

apps/log_reg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = "index"),
    url(r'^register$', views.register, name = "register"),
    url(r'^login$', views.login, name = "login"),
    url(r'^success$', views.success, name = "success"),
    url(r'^logout$', views.logout, name = "logout"),
]

apps/wish_list/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = "index"),
    url(r'^add_item$', views.add_item, name = "add_item"),
    url(r'^create_item/(?P<user_id>\d+)$', views.create_item, name = "create_item"),
    url(r'^delete_item/(?P<item_id>\d+)$', views.delete_item, name = "delete_item"),
    url(r'^item/(?P<item_id>\d+)$', views.item, name = "item"),
    url(r'^add_to_wishlist/(?P<user_id>\d+)/(?P<item_id>\d+)$', views.add_to_wishlist, name = "add_to_wishlist"),
    url(r'^remove_from_wishlist/(?P<user_id>\d+)/(?P<item_id>\d+)$', views.remove_from_wishlist, name = "remove_from_wishlist"),
]

apps/wish_list/models.py
from __future__ import unicode_literals

from django.db import models
from ..log_reg.models import Users

import datetime

# Create your models here.
class ItemManager(models.Manager):
    def create_item(self, postData, user_id):
        errors = []
        if len(postData["item"]) < 3:
            errors.append("Item name must be at least 3 characters")


        if not errors:
            user = Users.objects.get(id=user_id)
            try:
                wlist = WishList.objects.get(user=user)
            except:
                wlist = WishList.objects.create(user=user)

            new_item = self.create(name=postData["item"], user=user)
            new_item.wish_list.add(wlist)
            return (True, "Item successfully created.")
        else:
            return (False, errors)

class WishList(models.Model):
    user = models.OneToOneField(Users, related_name="wishlist_by_user")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Item(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(Users, related_name="items_by_user")
    wish_list = models.ManyToManyField(WishList, related_name="items_by_wishlist")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = ItemManager()

apps/wish_list/views.py
from django.shortcuts import render, redirect
from models import WishList, Item
from django.contrib import messages
from ..log_reg.models import Users

# Create your views here.
def index(request):
    if "current_user" not in request.session:
        messages.error(request, "Must be logged in to view this page.")
        return redirect("log_reg:index")

    curr_user = Users.objects.get(id=request.session["current_user"]["id"])

    context = {
    "other_items" : Item.objects.all(),
    "current_user" : curr_user
    }


    if WishList.objects.filter(user=curr_user):
        context["wishlist"] = WishList.objects.get(user=curr_user)
        context["other_items"] =  Item.objects.exclude(wish_list=curr_user.wishlist_by_user)


    return render(request, "wish_list/index.html", context)

def add_item(request):

    if "current_user" not in request.session:
        messages.error(request, "Must be logged in to view this page.")
        return redirect("log_reg:index")

    return render(request, "wish_list/add_item.html")

def create_item(request, user_id):

    if "current_user" not in request.session:
        messages.error(request, "Must be logged in to view this page.")
        return redirect("log_reg:index")

    item_added = Item.objects.create_item(request.POST, user_id)

    if item_added[0]:
        return redirect("wish_list:index")
    else:
        for mes in item_added[1]:
            messages.error(request, mes)
        return redirect("wish_list:add_item")

def add_to_wishlist(request, user_id, item_id):

    if "current_user" not in request.session:
        messages.error(request, "Must be logged in to view this page.")
        return redirect("log_reg:index")

    user = Users.objects.get(id=user_id)
    item = Item.objects.get(id=item_id)
    try:
        wlist = WishList.objects.get(user=user)
    except:
        wlist = WishList.objects.create(user=user)

    wlist.items_by_wishlist.add(item)

    return redirect("wish_list:index")

def remove_from_wishlist(request, user_id, item_id):

    if "current_user" not in request.session:
        messages.error(request, "Must be logged in to view this page.")
        return redirect("log_reg:index")

    user = Users.objects.get(id=user_id)
    item = Item.objects.get(id=item_id)
    wlist = WishList.objects.get(user=user)
    wlist.items_by_wishlist.remove(item)

    return redirect("wish_list:index")

def delete_item(request, item_id):

    if "current_user" not in request.session:
        messages.error(request, "Must be logged in to view this page.")
        return redirect("log_reg:index")

    item = Item.objects.get(id=item_id).delete()

    return redirect("wish_list:index")

def item(request, item_id):

    if "current_user" not in request.session:
        messages.error(request, "Must be logged in to view this page.")
        return redirect("log_reg:index")

    context = {
    "item":Item.objects.get(id=item_id),
    "wishlists": WishList.objects.filter(items_by_wishlist=Item.objects.get(id=item_id))
    }

    return render(request, "wish_list/item.html", context)

apps/wish_list/templates/wish_list/add_item.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Add Item</title>
  </head>
  <body>
    <h2>Hello, {{ request.session.current_user.name }}!</h2>
    <form action="{% url 'log_reg:logout' %}" method="post" style="display:inline-block;">
      {% csrf_token %}
      <input type="submit" name="logout" value="Logout">
    </form>
    <form action="{% url 'wish_list:index' %}" method="post" style="display:inline-block;">
      {% csrf_token %}
       <input type="submit" name="home" value="Home">
    </form>
    <h1>Create a New Wish List Item</h1>
    {% if messages %}
      {% for message in messages %}
        <h2>{{ message }}</h2>
      {% endfor %}
    {% endif %}
    <form action="{% url 'wish_list:create_item' user_id=request.session.current_user.id %}" method="post">
      {% csrf_token %}
      Item/Product: <input type="text" name="item">
      <input type="submit" name="add" value="Add">
    </form>
  </body>
</html>

apps/wish_list/templates/wish_list/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Your Wish List</title>
  </head>
  <body>
    <h2>Hello, {{ request.session.current_user.name }}!</h2>
    <form action="{% url 'log_reg:logout' %}" method="post" style="display:inline-block;">
      {% csrf_token %}
      <input type="submit" name="logout" value="Logout">
    </form>
    <h3>Your Wishlist</h3>
    <table border="1px" cellpadding="5px">
      <thead>
        <tr>
          <th>Item</th><th>Added By</th><th>Date Added</th><th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for item in wishlist.items_by_wishlist.all %}
        <tr>
          <td><a href="{% url 'wish_list:item' item_id=item.id %}">{{item.name}}</a></td><td>{{item.user.name}}</td><td>{{item.created_at}}</td>
          <td>{% if item.user == current_user %} <a href="{% url 'wish_list:delete_item' item_id=item.id %}">Delete</a> {% else %} <a href="{% url 'wish_list:remove_from_wishlist' user_id=request.session.current_user.id item_id=item.id %}">Remove from my wishlist</a> {% endif %}</td>
        </tr>
        {% endfor %}
      </tbody>

    </table>

    <h3>Other Users' Wishlist</h3>
    <table border="1px" cellpadding="5px">
      <thead>
        <tr>
          <th>Item</th><th>Added By</th><th>Date Added</th><th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for item in other_items %}
        <tr>
          <td><a href="{% url 'wish_list:item' item_id=item.id %}">{{item.name}}</a></td><td>{{item.user.name}}</td><td>{{item.created_at}}</td>
          <td><a href="{% url 'wish_list:add_to_wishlist' user_id=request.session.current_user.id item_id=item.id %}">Add to my wishlist</a></td>
        </tr>
        {% endfor %}
      </tbody>

    </table>


    <a href="{% url 'wish_list:add_item' %}">Add Item</a>

  </body>
</html>

apps/wish_list/templates/wish_list/item.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{item.name}}</title>
  </head>
  <body>
    <h2>Hello, {{ request.session.current_user.name }}!</h2>
    <form action="{% url 'log_reg:logout' %}" method="post" style="display:inline-block;">
      {% csrf_token %}
      <input type="submit" name="logout" value="Logout">
    </form>
    <form action="{% url 'wish_list:index' %}" method="post" style="display:inline-block;">
      {% csrf_token %}
       <input type="submit" name="home" value="Home">
    </form>
    <h1>{{item.name}}</h1>
    <p>Users who added this product/item under their wish list:</p>
    {% for wishlist in wishlists %}
      <p>{{wishlist.user.name}}</p>
    {% endfor %}
  </body>
</html>