Python_Black_Belt_01/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include("apps.log_reg.urls", namespace = "log_reg")),
    url(r'^wishlist/', include("apps.wish_list.urls", namespace = "wish_list")),
]

apps/log_reg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = "index"),
    url(r'^register$', views.register, name = "register"),
    url(r'^login$', views.login, name = "login"),
    url(r'^success$', views.success, name = "success"),
    url(r'^logout$', views.logout, name = "logout"),
]

apps/log_reg/models.py
from __future__ import unicode_literals

from django.db import models

import bcrypt, datetime


# Create your models here.
class UserManager(models.Manager):
    def add_user(self, postData):
        errors = []
        if len(postData["name"]) < 3:
            errors.append("Name must be at least 3 characters")
        if len(postData["username"]) < 3:
            errors.append("Username must be at least 3 characters")
        if len(postData["password"]) < 8:
            errors.append("Password must be at least 8 characters")
        if postData["password"] != postData["confirm_password"]:
            errors.append("Password and Confirm Password must match")
        if self.filter(username = postData["username"]):
            errors.append("This username has already been registered.")

        try:
            date_hired = datetime.datetime.strptime(postData["date_hired"], "%m/%d/%Y")
            if date_hired > datetime.datetime.now():
                errors.append("Date hired cannot be in the future.")
        except ValueError:
            errors.append("Please enter date hired in mm/dd/yyyy format.")

        if not errors:
            pw_hash = bcrypt.hashpw(postData["password"].encode(), bcrypt.gensalt())
            user = self.create(name=postData["name"], username=postData["username"], date_hired=date_hired, pw_hash = pw_hash)
            return (True, user)
        else:
            return (False, errors)

    def login(self, postData):
        try:
            user = Users.objects.get(username = postData["username"])
            if not bcrypt.checkpw(postData["password"].encode(), user.pw_hash.encode()):
                return (False, "Password incorrect")
        except:
            return (False, "Username is not registered")

        user = Users.objects.get(username=postData["username"])
        return (True, user)


class Users(models.Model):
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    date_hired = models.DateTimeField()
    pw_hash = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

apps/log_reg/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from models import Users

# Create your views here.
def index(request):

    return render(request, "log_reg/index.html")

def register(request):

    new_user = Users.objects.add_user(request.POST)

    if new_user[0]:
        request.session["current_user"] = {
        "id" : new_user[1].id,
        "name" : new_user[1].name,
        "username" : new_user[1].username
        }
        return redirect("log_reg:success")
    else:
        for mes in new_user[1]:
            messages.error(request, mes)
        return redirect("log_reg:index")

def login(request):

    new_user = Users.objects.login(request.POST)

    if new_user[0]:
        request.session["current_user"] = {
        "id" : new_user[1].id,
        "name" : new_user[1].name,
        "username" : new_user[1].username
        }
        return redirect("log_reg:success")
    else:
        messages.error(request, new_user[1])
        return redirect("log_reg:index")

def logout(request):

    del request.session["current_user"]

    return redirect("/")

def success(request):

    if "current_user" not in request.session:
        messages.error(request, "Must be logged in to view this page.")
        return redirect("log_reg:index")

    return render(request, "log_reg/success.html")

apps/log_reg/templates/log_reg/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Login and Registration</title>
  </head>
  <body>
    {% if messages %}
      {% for message in messages %}
        <h2>{{ message }}</h2>
      {% endfor %}
    {% endif %}
    <h2>Registration</h2>
    <p>All fields case sensitive</p>
    <form action="{% url 'log_reg:register' %}" method="post">
      {% csrf_token %}
      <label for="name">Name: <input type="text" name="name" id="name"></label>
      <label for="username">Username: <input type="text" name="username" id="username"></label>
      *Password should be at least 8 characters
      <label for="password">Password: <input type="password" name="password" id="password"></label>
      <label for="confirm_password">Confirm Password: <input type="password" name="confirm_password" id="confirm_password"></label>
      <label for="date_hired">Date Hired (in mm/dd/yyyy format): <input type="text" name="date_hired" id="date_hired" placeholder="mm/dd/yyyy"></label>
      <input type="submit" name="register" value="Register">
    </form>
    <h2>Login</h2>
    <p>All fields case sensitive</p>
    <form action="{% url 'log_reg:login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username: <input type="text" name="username" id="username"></label>
      <label for="password">Password: <input type="password" name="password" id="password"></label>
      <input type="submit" name="login" value="Login">
    </form>
  </body>
</html>
<!-- BP -->

apps/log_reg/templates/log_reg/success.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Success!</title>
  </head>
  <body>
    <h2>Success! Welcome, {{ request.session.current_user.name }}!</h2>
    <p>Successfully registered (or logged in)!</p>
    <form action="{% url 'log_reg:logout' %}" method="post">
      {% csrf_token %}
      <input type="submit" name="logout" value="Logout">
    </form>
    <a href="{% url 'wish_list:index' %}">Continue on to your wishlist!</a>
  </body>
</html>